server:
  port:8080

spring:
  application:
    name:user-service
  datasource: 
    url: jdbc:postgresql://host.docker.internal:9999/quik_searcher_user_db
    username: postgres
    password: "12345678"
    driver-class-name: org.postgresql.Driver
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
